services:
  - type: web
    name: zola-site
    env: static
    buildCommand: curl -L https://github.com/getzola/zola/releases/download/v${ZOLA_VERSION}/zola-v${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar xz && ./zola build
    publishDir: public
    envVars:
      - key: ZOLA_VERSION
        value: 0.17.2
